# Generated by Django 3.1.4 on 2021-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proid', models.IntegerField()),
                ('pronm', models.CharField(max_length=50)),
                ('propri', models.IntegerField()),
                ('proamt', models.IntegerField()),
                ('proi', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
