# Generated by Django 3.1.4 on 2021-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='profil',
            field=models.IntegerField(default=1),
        ),
    ]
