# Generated by Django 3.1.4 on 2021-06-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldpage', '0002_products_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrphoto', models.ImageField(upload_to='usrphotos/')),
            ],
        ),
    ]
