# Generated by Django 3.1.4 on 2021-06-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldpage', '0003_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='usrmail',
            field=models.EmailField(default='guest@domain.com', max_length=60),
        ),
        migrations.AddField(
            model_name='userimage',
            name='usrpass',
            field=models.CharField(default='12345678', max_length=50),
        ),
    ]
