# Generated by Django 3.1.4 on 2021-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldpage', '0004_auto_20210623_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrmail', models.EmailField(default='guest@domain.com', max_length=60)),
                ('usrpass', models.CharField(default='12345678', max_length=50)),
                ('usrprofile', models.ImageField(upload_to='usrprofile/')),
                ('usrphoto', models.ImageField(upload_to='usrphotos/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
