# Generated by Django 3.1.4 on 2021-06-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldpage', '0005_auto_20210623_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usrphoto',
            field=models.ImageField(blank=True, null=True, upload_to='usrphotos/'),
        ),
    ]
