# Generated by Django 3.1.4 on 2021-06-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldpage', '0007_auto_20210623_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=60)),
                ('usrph', models.ImageField(upload_to='usrphotos/')),
                ('usraddress', models.CharField(max_length=200)),
                ('usrphoneno', models.IntegerField()),
                ('usrprofile', models.ImageField(upload_to='usrprofile/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
