# Generated by Django 3.1.4 on 2021-06-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldpage', '0009_auto_20210628_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='usrphoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
