# Generated by Django 3.1.4 on 2021-08-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldpage', '0014_auto_20210807_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='proierased',
            field=models.ImageField(default='D:\\OpenSource\\JewelleryStore\\WhatsApp Image 2021-08-08 at 12.50.34 AM.jpeg', upload_to='uploads/'),
        ),
    ]
